version: '3.8'

services:
  wheels:
    image: 10.100.10.116:5000/wheels-img
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 15s
      placement:
        constraints: []
    ports:
      - "50052:60051"
    environment:
      - PORT=60051
      - HEALTHCHECK_URI=http://127.0.0.1:60051/
    networks:
      - wheels-net
    volumes:
      - wheels-data:/data

networks:
  wheels-net:
    driver: overlay

volumes:
  wheels-data: