version: '3.8'

services:
  wheels-dev:
    image: 10.100.10.116:5000/wheels-dev-prod
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 15s
      placement:
        constraints: []
    ports:
     - target: 60150
        published: 50150
        protocol: tcp
        mode: host
    environment:
      - PORT=60150
      - HEALTHCHECK_URI=http://127.0.0.1:60150/
#      - JVM_HEAPSIZE=1024
#      - BOX_SERVER_DEBUG=true
    networks:
      - wheels-net
    volumes:
      - shared-images:/app/public/images
      - shared-files:/app/public/files
      - shared-sitemap-prod:/app/public/sitemap
      - wheels-data:/data

networks:
  wheels-net:
    driver: overlay

volumes:
  shared-images:
    external: true
  shared-files:
    external: true
  shared-sitemap-prod:
    external: true
  wheels-data:
