version: '3.8'

services:
  wheels-dev:
    image: 10.100.10.116:5000/wheels-dev-prod
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 15s
      placement:
        constraints: []
    ports:
      - "50150:60150"
    environment:
      - PORT=60151
      - HEALTHCHECK_URI=http://127.0.0.1:60150/
    networks:
      - wheels-net
    volumes:
      - shared-images:/app/public/images
      - shared-files:/app/public/files
      - wheels-data:/data

networks:
  wheels-net:
    driver: overlay

volumes:
  shared-images:
    external: true
  shared-files:
    external: true
  wheels-data:
