version: '3.8'

services:
  wheels-dev:
    image: 10.100.10.116:5000/wheels-dev-stage
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 15s
      placement:
        constraints: []
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - target: 60151
        published: 50151
        protocol: tcp
        mode: ingress       # <-- enables Docker routing mesh
    environment:
      - PORT=60151
      - HEALTHCHECK_URI=http://127.0.0.1:60151/
    networks:
      - wheels_overlay_net
    volumes:
      - shared-images:/app/public/images
      - shared-files:/app/public/files
      - shared-sitemap:/app/public/sitemap
      - shared-dev-docs:/app/docs/3.0.0/guides
      - shared-json-folder:/app/public/json
      - wheels-data:/data

networks:
  wheels_overlay_net:
    driver: overlay
    attachable: true      # optional: allows manual container attachment

volumes:
  shared-images:
    external: true
  shared-files:
    external: true
  shared-sitemap:
    external: true
  shared-dev-docs:
    external: true
  shared-json-folder:
    external: true
  wheels-data:
