name: Deploy to Docker Swarm

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, wheels]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: |
          box install
          docker build -t ${{ secrets.REGISTRY_IP }}:${{ secrets.PORT }}/wheels-img .
          docker push ${{ secrets.REGISTRY_IP }}:${{ secrets.PORT }}/wheels-img
          scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SWARM_MANAGER_IP }}:/home/${{ secrets.SSH_USER }}/wheels.dev

  deploy:
    runs-on: [self-hosted, linux, wheels]
    needs: deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SWARM_MANAGER_IP }} << 'EOF'
            cd /home/${{ secrets.SSH_USER }}/wheels.dev
            docker stack deploy -c docker-compose.yml wheels-dev
          EOF
