name: Wheels.dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-to-docker-swarm:
    runs-on: [self-hosted, Linux, pai]

    steps:
      - name: Checkout Repository
        id: Checkout-Repository
        uses: actions/checkout@v4

      - name: Create .env File
        id: Create-Env-File
        run: |
          mv .env-testing .env

      - name: Install Dependencies
        id: Install-Dependencies
        run: |
          box install
          
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login "${{ secrets.DOCKER_HUB_IP }}":"${{ secrets.DOCKER_HUB_PORT}}" -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        
      - name: Push Docker Image
        id: Push-Docker-Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_IP }}:${{ secrets.DOCKER_HUB_PORT}}/wheels-img .
          docker push ${{ secrets.DOCKER_HUB_IP }}:${{ secrets.DOCKER_HUB_PORT}}/wheels-img

      - name: Deploy to Docker Swarm
        id: Deploy-to-Docker-Swarm
        run: |
          docker pull ${{ secrets.DOCKER_HUB_IP }}:${{ secrets.DOCKER_HUB_PORT}}/wheels-img
          docker stack deploy -c docker-compose.yml wheels-dev
