name: Wheels.dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, prod]

    env:
      APP_DIR: /home/wheels-1/wheels.dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare application directory
        run: |
          mkdir -p "$APP_DIR"
          rsync -av --delete ./ "$APP_DIR/"

      - name: Create Environment Files
        working-directory: ${{ env.APP_DIR }}
        run: |
          cp ./deploy/prod/.env .
          cp ./deploy/prod/server.json .

      - name: Install Wheels CLI
        working-directory: ${{ env.APP_DIR }}
        run: |
          box install wheels-cli

      - name: Install Dependencies
        working-directory: ${{ env.APP_DIR }}
        run: |
          box install

      - name: Restart Wheels Server
        working-directory: ${{ env.APP_DIR }}
        run: |
          box server stop || true
          echo "cd $APP_DIR && box server start" | at now + 1 minute
          echo "Server scheduled to start in 1 minute"


#      - name: Post Slack Message
#        id: Post-Slack-Message
#        uses: act10ns/slack@v2
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
#          status: ${{ job.status }}
#          steps: ${{ toJson(steps) }}
#          channel: '#wheels-dev'
#        if: always()
