name: Wheels.dev
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, stage]
    steps:
      - name: Checkout Repository
        id: Checkout-Repository
        uses: actions/checkout@v4
        
      - name: Create Environment Files
        id: Create-Environment-Files
        run: |
          cp ./deploy/stage/.env ./
          cp ./deploy/stage/server.json ./

      - name: Install Wheels-cli
        id: Install-Wheels-cli
        run: |
          box install wheels-cli

      - name: Install Dependencies
        id: Install-Dependencies
        run: |
          box install

      - name: Restart server
        id: Restart-server
        run: |
          box server stop || true
          box server start